version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/protractorTest

    steps:
      - checkout
      
      - run:
			name: Testing the project
			command: yarn install
	  - run:
			name: Testing the project
			command: yarn test